// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGysQjQCdTFLpBgpbM4fNrddsq4r2eFGY',
    appId: '1:309875581161:web:698e10e2d18882277cd078',
    messagingSenderId: '309875581161',
    projectId: 'tongbok-2e30e',
    authDomain: 'tongbok-2e30e.firebaseapp.com',
    storageBucket: 'tongbok-2e30e.appspot.com',
    measurementId: 'G-3S1KK1FC8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALCV-okvARaLLuLCGZ_lqWHsx8VoCkBFw',
    appId: '1:309875581161:android:8ea8a3dce8ebbebe7cd078',
    messagingSenderId: '309875581161',
    projectId: 'tongbok-2e30e',
    storageBucket: 'tongbok-2e30e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN_DkDmcUrAD6gSyrdlp_4vKOqvKwMgE4',
    appId: '1:309875581161:ios:602dc721449fc61e7cd078',
    messagingSenderId: '309875581161',
    projectId: 'tongbok-2e30e',
    storageBucket: 'tongbok-2e30e.appspot.com',
    iosBundleId: 'com.example.tongbokapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN_DkDmcUrAD6gSyrdlp_4vKOqvKwMgE4',
    appId: '1:309875581161:ios:602dc721449fc61e7cd078',
    messagingSenderId: '309875581161',
    projectId: 'tongbok-2e30e',
    storageBucket: 'tongbok-2e30e.appspot.com',
    iosBundleId: 'com.example.tongbokapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGysQjQCdTFLpBgpbM4fNrddsq4r2eFGY',
    appId: '1:309875581161:web:4c1a86606a0eea2d7cd078',
    messagingSenderId: '309875581161',
    projectId: 'tongbok-2e30e',
    authDomain: 'tongbok-2e30e.firebaseapp.com',
    storageBucket: 'tongbok-2e30e.appspot.com',
    measurementId: 'G-ZMXH057NEV',
  );
}
